# Generated by Django 4.1.7 on 2023-03-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department_id',
            new_name='department',
        ),
    ]
