# Generated by Django 4.1.7 on 2023-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1', 'First Level'), ('2', 'Second Level'), ('3', 'Third Level'), ('4', 'Fourth Level')], default='1', max_length=10),
        ),
    ]
