# Generated by Django 4.1.7 on 2023-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
